In [1]:
# pip install numpy
import numpy as np


In [4]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
np.zeros([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
np.arange(4,20) #[4, 20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [22]:
np.arange(-5,-1)

array([-5, -4, -3, -2])

In [26]:
np.arange(0,3.1,.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [28]:
arreglo_pares = np.arange(0,3,0.7)

In [32]:
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

5
5
(2, 3, 4)


In [37]:
arreglo_pares.reshape(1,1,5)

array([[[0. , 0.7, 1.4, 2.1, 2.8]]])

In [39]:
arreglo_24_elementos = np.arange(24)
arreglo_24_elementos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [41]:
arreglo_24_elementos.reshape(1,24)
arreglo_24_elementos.reshape(24,1)
arreglo_24_elementos.reshape(2,12)
arreglo_24_elementos.reshape(12,2)
arreglo_24_elementos.reshape(8,3)
arreglo_24_elementos.reshape(3,8)
arreglo_24_elementos.reshape(6,4)
arreglo_24_elementos.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [43]:
# suma
a + b

array([15, 15, 15])

In [44]:
# resta
a - b

array([5, 5, 5])

In [45]:
# multiplicación
a * b

array([50, 50, 50])

In [46]:
# división
a / b

array([2., 2., 2.])

In [73]:
a = np.arange(1,32,2.1).reshape(3,1,5)
b = np.arange(-4,18,1.5).reshape(3,1,5)
print(a)
print(b)

[[[ 1.   3.1  5.2  7.3  9.4]]

 [[11.5 13.6 15.7 17.8 19.9]]

 [[22.  24.1 26.2 28.3 30.4]]]
[[[-4.  -2.5 -1.   0.5  2. ]]

 [[ 3.5  5.   6.5  8.   9.5]]

 [[11.  12.5 14.  15.5 17. ]]]


In [69]:
# suma
a + b

array([[[-3. ,  0.6,  4.2,  7.8, 11.4]],

       [[15. , 18.6, 22.2, 25.8, 29.4]],

       [[33. , 36.6, 40.2, 43.8, 47.4]]])

In [70]:
# resta
a - b

array([[[ 5. ,  5.6,  6.2,  6.8,  7.4]],

       [[ 8. ,  8.6,  9.2,  9.8, 10.4]],

       [[11. , 11.6, 12.2, 12.8, 13.4]]])

In [60]:
# multiplicación
a * b

array([-4., -5., -3.])

In [71]:
# división
a / b

array([[[-0.25      , -1.24      , -5.2       , 14.6       ,
          4.7       ]],

       [[ 3.28571429,  2.72      ,  2.41538462,  2.225     ,
          2.09473684]],

       [[ 2.        ,  1.928     ,  1.87142857,  1.82580645,
          1.78823529]]])

In [72]:
# módulo
a % b

array([[[-3. , -1.9, -0.8,  0.3,  1.4]],

       [[ 1. ,  3.6,  2.7,  1.8,  0.9]],

       [[ 0. , 11.6, 12.2, 12.8, 13.4]]])

In [76]:
a + 10
a - 7
a * 10
a / 4

array([[[0.25 , 0.775, 1.3  , 1.825, 2.35 ]],

       [[2.875, 3.4  , 3.925, 4.45 , 4.975]],

       [[5.5  , 6.025, 6.55 , 7.075, 7.6  ]]])

In [77]:
arreglo_muestra = np .arange(20).reshape(5,2,2)

In [121]:
resp = (arreglo_muestra > 6) & (arreglo_muestra < 14) & (arreglo_muestra%2==0)
print(arreglo_muestra[resp])

[ 8 10 12]


In [122]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [123]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [124]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [125]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [126]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [127]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [128]:
arreglo_doce.sum()

66

In [129]:
arreglo_doce.min()

0

In [130]:
arreglo_doce.max()

11

In [134]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [135]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [136]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [137]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])