In [1]:
import numpy as np

In [3]:
arreglo_0_a_90_grados = np.array([0, 30, 45, 60, 90])
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [4]:
radianes = arreglo_0_a_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [6]:
np.sin(radianes)
np.cos(radianes)
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [11]:
arreglo_random = np.random.randint(
    10 # enteros + hasta
)
arreglo_random ## [0, 11[]

8

In [12]:
arreglo_random = np.random.randint(
    0, # Minimo
    11, # Maximo
    3 # Número de aleartorios
)
arreglo_random #[-1, 2[

array([10,  7,  3])

In [13]:
arreglo_random.mean()

6.666666666666667

In [17]:
np.median(arreglo_random)
np.std(arreglo_random)
np.var(arreglo_random)
np.mean(arreglo_random)

6.666666666666667

2.8674417556808756