In [1]:
import numpy as np

In [2]:
arreglo_cero_diez = np.arange(0, 11) ** 2
arreglo_cero_diez

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [3]:
arreglo_cero_diez[0:7]

array([ 0,  1,  4,  9, 16, 25, 36])

In [4]:
arreglo_cero_diez[-6:-1]

array([25, 36, 49, 64, 81])

In [5]:
arreglo_pares = (arreglo_cero_diez[arreglo_cero_diez%2 == 0])
arreglo_pares

array([  0,   4,  16,  36,  64, 100])

In [6]:
arreglo_cero_diez[::-2]

array([100,  64,  36,  16,   4,   0])

In [9]:
arreglo_cero_diez.mean()

35.0

In [12]:
np.median(arreglo_cero_diez)

25.0

In [13]:
np.var(arreglo_cero_diez)

1078.0